# Site settings
title: Open Source Design - Patterns
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/patterns/" # the subpath of your site, e.g. /blog/
url: "http://opensourcedesign.net" # the base hostname & protocol for your site
twitter_username: opensrcdesign
github_username:  opensourcedesign

# Build settings
markdown: kramdown
permalink: /:month-:day-:year/:title.html

kramdown:
  input: GFM

# Prose Config - what is seen at https://edit.opensourcedesign.net
# Docs: https://github.com/prose/prose/wiki/Prose-Configuration
prose:
  rooturl: ''
  ignore:
    - '_config.yml'
